### ISSUE TITLE
Pre-trained model?

### ISSUE THREAD

**Issue by acul3** [yuwfan/FILTER#1]
i can't download pre trained model from 'bash download _data.sh'

it says not exist 

are this link valid ?

`https://convaisharables.blob.core.windows.net/filter/outputs/phase1/xquad/config.json
https://convaisharables.blob.core.windows.net/filter/outputs/phase1/xquad/pytorch_model.bin.json`

**Comment by yuwfan** [comment]
Thanks for reporting the issue. Please check the updated repo and use the link below:
https://convaisharables.blob.core.windows.net/filter/data/outputs/phase1/xquad/config.json https://convaisharables.blob.core.windows.net/filter/data/outputs/phase1/xquad/pytorch_model.bin
